name: ForceItemPlugin
version: 1.0
main: de.samuel.ForceItemPlugin
api-version: 1.21
author: Samuel
description: Force Item Battle
commands:
  fib:
    description: starts/stops the Force-Item-Battle
    usage: /fib <start|stop>
